//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется E:\DropSvn\flylinkdc\FlylinkDC.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DCLS_PAGE                   101
#define IDD_GENERAL_PAGE                102
#define IDR_HTML_REMOTECONTROLPAGE      103
#define IDD_LINE                        104
#define IDD_ADVANCED_PAGE               105
#define IDD_DOWNLOAD_PAGE               106
#define IDD_SHARE_PAGE                  107
#define IDD_APPEARANCE_PAGE             108
#define IDD_FAVORITEHUB                 109
#define IDD_LOG_PAGE                    110
#define IDD_USER_COMMAND                111
#define IDR_FLATTAB                     112
#define IDR_MAINFRAME                   113
#define IDR_INTERNET_HUBS               114
#define IDR_RECENT_HUBS                 115
#define IDR_FAVORITES                   116
#define IDR_FAVORITE_USERS              117
#define IDR_QUEUE                       118
#define IDR_FINISHED_DL                 119
#define IDR_UPLOAD_QUEUE                120
#define IDR_FINISHED_UL                 121
#define IDR_NETWORK_STATISTICS_ICON     122
#define IDR_SEARCH                      123
#define IDR_ADLSEARCH                   124
#define IDR_SPY                         125
#define IDR_NOTEPAD                     126
#define IDR_RSS                         127
#define IDR_PORTAL_BROWSER              128
#define IDR_HUB                         129
#define IDR_HUB_OFF                     130
#define IDR_PRIVATE                     131
#define IDR_PRIVATE_OFF                 132
#define IDR_BANNED_ONLINE               133
#define IDR_BANNED_OFF                  134
#define IDR_FILE_LIST                   135
#define IDR_FILE_LIST_OFF               136
#define IDR_CDM                         137
#define IDR_MAGNET                      138
#define IDR_ERROR                       139
#define IDR_SHUTDOWN                    140
#define IDR_TUSER                       141
#define IDR_PURGE                       143
#define IDR_PAUSE                       144
#define IDD_ADLS_PROPERTIES             145
#define IDD_UCPAGE                      146
#define IDD_SOUNDS_PAGE                 147
#define IDD_FAKEDETECT_PAGE             148
#define IDD_OPERACOLORS_PAGE            149
#define IDD_AVIPREVIEW_PAGE             150
#define IDD_PREVIEW                     151
#define IDD_TOOLBAR_PAGE                152
#define IDD_FAVORITE_DIRS_PAGE          153
#define IDD_CLIENT_PROFILE              154
#define IDD_MAGNET                      155
#define IDD_HASH_PROGRESS               156
#define IDD_POPUPS_PAGE                 157
#define IDD_SDC_PAGE                    158
#define IDD_USERLIST_COLOURS_PAGE       159
#define IDD_HUB_LIST                    160
#define IDD_WINDOWS_PAGE                161
#define IDD_EMOTICONS_DLG               162
#define IDD_NETWORK_PAGE                163
#define IDD_QUEUE_PAGE                  164
#define IDD_CERTIFICATES_PAGE           165
#define IDD_PARAM_DLG                   166
#define IDD_CHANGE_PASS                 168
#define IDD_FAVORITEDIR                 169
#define IDD_CLIENTS_PAGE                170
#define IDD_DETECTION_ENTRY             171
#define IDD_RSS_PAGE                    172
#define IDD_DEFAULT_CLICK_PAGE          173
#define IDD_RSS_SET_FEED                175
#define IDD_PROXY_PAGE                  176
#define IDD_TABS_PAGE                   177
#define IDD_PRIORITY_PAGE               178
#define IDR_SPLASH                      179
#define IDR_SPLASH_9MAY                 180
#define IDR_TOOLBAR                     181
#define IDR_TOOLBAR_HL                  182
#define IDR_TOOLBAR_MINI                183
#define IDR_PLAYERS_CONTROL             184
#define IDR_PLAYERS_CONTROL_HL          185
#define IDR_PLAYERS_CONTROL_MINI        186
#define IDR_SETTINGS_ICONS              187
#define IDR_USERS                       188
#define IDR_FLAGS                       189
#define IDR_ARROWS                      190
#define IDR_TSPEEDS                     191
#define IDR_TSPEEDS_BW                  192
#define IDR_SPEEDS                      193
#define IDR_FOLDERS                     194
#define IDR_SEARCH_TYPES                195
#define IDR_STATE                       196
#define IDR_FAV_USERS_STATES            197
#define IDR_SMILE                       198
#define IDD_FAVHUBGROUPS                199
#define IDR_SENDMESSAGE                 200
#define IDR_BOLD                        201
#define IDR_BOLD_ICON                   202
#define IDR_STRIKE                      203
#define IDR_STRIKE_ICON                 204
#define IDR_UNDERLINE                   205
#define IDR_ITALIC                      206
#define IDR_TRANSCODE                   207
#define IDD_CHECKTARGETDLG              208
#define IDR_STATE_USERS                 209
#define IDR_SENDMESSAGES_ICON           210
#define IDR_SMILE_ICON                  211
#define IDR_MULTI_CHAT_ICON             212
#define IDR_ITALIC_ICON                 213
#define IDR_TRANSCODE_ICON              214
#define IDR_UNDERLINE_ICON              215
#define IDD_UPDATE_PAGE                 216
#define IDR_AUTOUPDATE                  217
#define IDR_SPLASH_NY1                  218
#define IDR_SPLASH_NY2                  219
#define IDR_CLOSE_PNG                   220
#define IDD_UPDATE_DLG                  221
#define IDD_DCLS_GENERATOR              222
#define IDR_DCLST                       223
#define IDD_FILE_SHARE_PAGE             224
#define IDD_WIZARD_STARTUP              225
#define IDD_WIZARD_NICK                 226
#define IDD_WIZARD_DOWNLOAD             227
#define WM_CENTER_ALL                   229
#define IDD_WIZARD_SHARE                230
#define IDD_WIZARD_NET_IP               231
#define IDD_WIZARD_NET_ACTIVE           232
#define IDD_UPNPCHECK                   237
#define IDD_WIZARD_NETA_TESTSETUP       238
#define IDR_ISP_HUBLIST                 239
#define IDD_SPEEDLIMIT_DLG              240
#define IDD_INTEGRATION_PAGE            241
#define IDR_SPLASH_WINTER               242
#define IDD_INT_PREVIEW_PAGE            246
#define IDD_PREVIEW_LOG_DLG             247
#define IDD_LOCATIONS_PAGE              248
#define IDD_PROVIDERS_PAGE              249
#define IDD_EMPTY_PAGE                  250
#define FAKE_SET                        251
#define FAKE_SET2                       252
#define WEBSERVER_SOCKET_MESSAGE        254
#define IDR_TRAY_AND_TASKBAR_PM         255
#define IDR_TRAY_AND_TASKBAR_NO_PM      256
#define IDD_LIMIT_PAGE                  257
#define IDD_TEXT_STYLES_PAGE            258
#define IDD_KICK                        259
#define IDD_MISC_PAGE                   260
#define IDD_MESSAGES_PAGE               261
#define IDD_RANGES_PAGE                 262
#define IDD_REMOTE_CONTROL              263
#define IDD_WEBSERVER_PAGE              264
#define IDD_REMOTE_CONTROL_PAGE         265
#define IDD_SLOT_PAGE                   266
#define IDD_ADD_MAGNET                  267
#define IDD_MESSAGES_CHAT_PAGE          268
#define IDR_FLY_SERVER_CONFIG           269
#define IDD_REBUILD_MEDIAINFO_PROGRESS  270
#define IDR_FLYLINK_PNG                 272
#define IDR_MAGNET_PNG                  273
#define IDR_SWITCH_PANELS_ICON          275
#define IDR_ICON_SUCCESS_ICON           276
#define IDR_ICON_FAIL_ICON              277
#define IDR_ICON_WARN_ICON              278
#define IDR_FLY_SERVER_SENSOR           279
#define IDD_FLY_SERVER_DIALOG           280
#define IDR_MEDIAFILES                  281
#define IDR_SPLASH_FOOLS_DAY            282
#define IDR_IPGRANT_EXAMPLE             283
#define IDR_IPGUARD_EXAMPLE             284
#define IDR_IPTRUST_EXAMPLE             285
#define IDD_ABOUTCMDS                   286
#define IDD_ABOUTTABS                   287
#define IDD_SHARE_MISC_PAGE             288
#define IDD_FLY_PROGRESS                289
#define IDD_SEARCH_PAGE                 290
#define IDR_COLOR_ICON                  291
#define IDR_ICON_QUESTION_ICON          292
#define IDR_ICON_PAUSE_ICON             293
#define IDD_LOCATION_DIALOG             294
#define IDR_ICON_MEDICAL_BAG            295
#define IDR_ICON_THERMOMETR_BAG         296
#define IDR_ISP_HUB_LIST_EXAMPLE        297
#define IDR_ICON_FIREWALL               298
#define IDR_HUB_FLYLINKDC               299
#define IDD_ABOUTSTAT                   300
#define IDC_FILETYPES                   1000
#define IDC_TRAY_SHOW                   1001
#define IDC_COPY_HUB                    1002
#define IDC_REMOVE_OFFLINE              1003
#define IDC_DISABLE_SOUNDS              1004
#define IDC_CDMDEBUG_WINDOW             1005
#define IDC_CONNECT_ALL                 1006
#define IDC_DISCONNECT_ALL              1007
#define IDC_COLLAPSE_ALL                1008
#define IDC_EXPAND_ALL                  1009
#define IDC_COPY_HUBNAME                1010
#define IDC_COPY_HUBADDRESS             1011
#define IDC_MENU_SLOWDISCONNECT         1012
#define IDC_DEBUG_IP_FILTER_TEXT        1013
#define IDC_DEBUG_INCLUDE_FILTER_TEXT   1014
#define IDC_DEBUG_EXCLUDE_FILTER_TEXT   1015
#define IDC_USER_CMD_PREVIEW            1016
#define IDC_CLEAR                       1017
#define IDC_PUB_LIST_DROPDOWN           1018
#define IDC_SEARCH_PAUSE                1019
#define IDC_HUBLIST                     1020
#define IDC_EMOT                        1021
#define IDC_OPEN_MY_LIST                1022
#define IDC_SERVER                      1023
#define IDC_EXTERNAL_IP                 1024
#define IDC_TRAY_LIMITER                1025
#define IDC_DEFAULT_GATEWAY_IP          1025
#define IDC_FILES                       1026
#define IDC_SITES_FLYLINK_TRAC          1027
#define IDC_RECONNECT_DISCONNECTED      1028
#define IDC_WINAMP_BACK                 1029
#define IDC_WINAMP_PLAY                 1030
#define IDC_WINAMP_STOP                 1031
#define IDC_WINAMP_PAUSE                1032
#define IDC_WINAMP_NEXT                 1033
#define IDC_WINAMP_VOL_UP               1034
#define IDC_WINAMP_VOL_DOWN             1035
#define IDC_WINAMP_VOL_HALF             1036
#define IDC_WINAMP_SPAM                 1037
#define IDC_CLOSE_ALL_HUBS              1038
#define IDC_CLOSE_HUBS_BELOW            1039
#define IDC_CLOSE_HUBS_NO_USR           1040
#define IDC_DOWNCONN_SPIN               1041
#define IDC_MAX_MSG_LENGTH_SPIN         1042
#define IDC_GUIDE                       1044
#define IDC_TOPMOST                     1046
#define IDC_LOCK_TOOLBARS               1047
#define IDC_KICK_USERS                  1048
#define IDC_COPY_BEGIN                  1049
#define IDC_COPY_END                    1050
#define IDC_BTN_ABORT                   1051
#define IDC_BROWSE_PRIVATE_KEY          1052
#define IDC_BROWSE_CERTIFICATE          1053
#define IDC_BROWSE_TRUSTED_PATH         1054
#define IDC_GENERATE_CERTS              1055
#define IDC_TLS_CERTIFICATE_FILE        1056
#define IDC_TLS_OPTIONS                 1057
#define IDC_DISABLE_POPUPS              1058
#define IDC_REFRESH                     1059
#define IDC_NICK                        1060
#define IDC_EMAIL                       1061
#define IDC_DESCRIPTION                 1062
#define IDC_REFRESH_HUB_LIST            1063
#define IDC_USERS                       1064
#define IDC_ACTIVE                      1065
#define IDC_CONNECTION                  1066
#define IDC_PASSIVE                     1067
#define IDC_GENDER                      1068
#define IDC_PORT                        1069
#define IDC_DIRECTORIES                 1070
#define IDC_PORT_TCP                    1071
#define IDC_REMOVE_ALL                  1072
#define IDC_UPDATE_IP_INTERVAL          1073
#define IDC_ADD                         1074
#define IDC_REMOVE                      1075
#define IDC_TOTAL                       1076
#define IDC_SLOTS                       1077
#define IDC_SLOTSPIN                    1078
#define IDC_TRANSFERS                   1079
#define IDC_DOWNLOADDIR                 1080
#define IDC_CONNECT                     1081
#define IDC_BROWSEDIR                   1082
#define IDC_RESULTS                     1083
#define IDC_LINE                        1084
#define IDC_EXTRA_SLOTS2                1085
#define IDC_DOWNLOADDIRTO               1086
#define IDC_EXTRASPIN                   1087
#define IDC_PRIVATE_MESSAGE             1088
#define IDC_VERSION                     1089
#define IDC_GETLIST                     1090
#define IDC_EDIT                        1092
#define IDC_NOTEPAD                     1093
#define IDC_AWAY                        1094
#define IDC_SEARCH_ALTERNATES           1095
#define IDC_SELWINCOLOR                 1096
#define IDC_SELTEXT                     1097
#define IDC_SHAREHIDDEN                 1098
#define IDC_SHAREVIRTUAL                1099
#define IDC_QUEUE                       1100
#define IDC_SHARESYSTEM                 1101
#define IDC_HUBNICK                     1102
#define IDC_HUBPASS                     1103
#define IDC_NEWFAV                      1104
#define IDC_HUBNAME                     1105
#define IDC_SOURCE_TYPE                 1106
#define IDC_RAW_ONE                     1107
#define IDC_SIZE_TYPE                   1108
#define IDC_RAW_TWO                     1109
#define IDC_RAW_THREE                   1110
#define IDC_HUBDESCR                    1111
#define IDC_HUBADDR                     1112
#define IDC_RAW_FOUR                    1113
#define IDC_SETTINGS_LIST_CONFIG        1114
#define IDC_FORCE                       1115
#define IDC_RAW_FIVE                    1116
#define IDC_BUFFERSIZE                  1117
#define IDC_LANGUAGE                    1118
#define IDC_BROWSE                      1119
#define IDC_THANKS                      1120
#define IDC_DOWNLOADS                   1121
#define IDC_THIRD_PARTY_SOFTWARE        1122
#define IDC_SLOTSSPIN                   1123
#define IDC_UDP_DHT_SSL_STAT            1124
#define IDC_MAXSPEED                    1125
#define IDC_SPEEDSPIN                   1126
#define IDC_FAVUSERS                    1127
#define IDC_PROXY                       1128
#define IDC_ADD_TO_FAVORITES            1129
#define IDC_FILESPIN                    1130
#define IDC_HELP_HOMEPAGE               1131
#define IDC_LOG_DIRECTORY               1132
#define IDC_BROWSE_LOG                  1133
#define IDC_HELP_DISCUSS                1134
#define IDC_HELP_FAQ                    1135
#define IDC_SEARCH_SPY                  1136
#define IDC_LATEST                      1137
#define IDC_PRIVATE_MESSAGE_BEEP        1138
#define IDC_PRIVATE_MESSAGE_BEEP_OPEN   1139
#define IDC_MIN_UPLOAD_SPEED            1140
#define IDC_SETTINGS_TYPE               1141
#define IDC_MIN_UPLOAD_SPIN             1142
#define IDC_CHEVRON                     1143
#define IDC_OPEN_FILE_LIST              1144
#define IDC_TOTALS                      1145
#define IDC_TOTAL_DOWNLOAD              1146
#define IDC_SEARCH                      1147
#define IDC_RATIO                       1148
#define IDC_TOTALS2                     1149
#define IDC_TOTAL_UPLOAD                1150
#define IDC_CLOSE_WINDOW                1151
#define IDC_FIND                        1152
#define IDC_NEXT                        1153
#define IDC_FINISHED                    1154
#define IDC_TEMP_DOWNLOAD_DIRECTORY     1155
#define IDC_BROWSETEMPDIR               1156
#define IDC_SOCKS_RESOLVE               1157
#define IDC_PROGRESS_BUMPED             1158
#define IDC_BT_MAGNET_HANDLER           1159
#define IDC_REMOVEALL                   1160
#define IDC_NATT                        1161
#define IDC_BROWSE_BT_PROGRAMM          1162
#define IDC_UPDATE_IP_DHT               1163
#define IDC_SETTINGS_USE_DHT_NOTANSWER  1164
#define IDC_SOCKS_SERVER                1165
#define IDC_SOCKS_PORT                  1166
#define IDC_SOCKS_USER                  1167
#define IDC_SOCKS_PASSWORD              1168
#define IDC_FREESLOTS                   1169
#define IDC_TTHONLY                     1170
#define IDC_COPY_NICK                   1171
#define IDC_ADVANCED_BOOLEANS           1172
#define IDC_ADD_MENU                    1173
#define IDC_MOVE                        1174
#define IDC_REMOVE_MENU                 1175
#define IDC_MENU_ITEMS                  1176
#define IDC_CHANGE_MENU                 1177
#define IDC_NAME                        1178
#define IDC_COMMAND                     1179
#define IDC_PROGRESS_OVERRIDE           1180
#define IDC_HUB                         1181
#define IDC_PROGRESS_OVERRIDE2          1182
#define IDC_SHUTDOWNTIMEOUT             1183
#define IDC_PROGRESS_SEGMENT_SHOW       1184
#define IDC_SETTINGS_ODC_MENUBAR_RIGHT  1185
#define IDC_APPEARANCE_BOOLEANS         1186
#define IDC_SETTINGS_ODC_MENUBAR_LEFT   1187
#define IDC_DEFAULT_AWAY_MESSAGE        1188
#define IDC_INTERVAL                    1189
#define IDC_OPERACOLORS_BOOLEANS        1190
#define IDC_CLOSE_DISCONNECTED          1191
#define IDC_MATCH                       1192
#define IDC_OPEN_FOLDER                 1193
#define IDC_MAX_TAB_ROWS                1194
#define IDC_OPEN_FILE                   1195
#define IDC_SETTINGS_ODC_MENUBAR_BUMPED 1196
#define IDC_FILE_ADL_SEARCH             1197
#define IDC_SHUTDOWN                    1198
#define IDC_ADLLIST                     1199
#define IDC_MOVE_UP                     1200
#define IDC_MOVE_DOWN                   1201
#define IDC_HUBUSERDESCR                1202
#define IDC_FINISHED_UL                 1203
#define IDC_HUBEMAIL                    1204
#define IDC_SEARCH_STRING               1205
#define IDC_SEARCH_HISTORY              1206
#define IDC_HUBAWAY                     1207
#define IDC_DEST_DIR                    1208
#define IDC_IS_ACTIVE                   1209
#define IDC_MIN_FILE_SIZE               1210
#define IDC_MAX_FILE_SIZE               1211
#define IDC_AUTOQUEUE                   1212
#define IDC_GO_TO_DIRECTORY             1213
#define IDC_IS_FORBIDDEN                1214
#define IDC_MATCH_QUEUE                 1215
#define IDC_VIEW_AS_TEXT                1216
#define IDC_PAGE                        1217
#define IDC_NET_STATS                   1218
#define IDC_SETTINGS_PERSONAL_INFORMATION 1219
#define IDC_SETTINGS_NICK               1220
#define IDC_SETTINGS_EMAIL              1221
#define IDC_SETTINGS_DESCRIPTION        1222
#define IDC_SETTINGS_ODC_SHUTDOWNTIMEOUT 1223
#define IDC_COMMAND_DESCRIPTION         1224
#define IDC_SETTINGS_IP                 1225
#define IDC_SETTINGS_PORT               1226
#define IDC_SETTINGS_SOCKS5_IP          1227
#define IDC_SETTINGS_SOCKS5_PORT        1228
#define IDC_SETTINGS_SOCKS5_USERNAME    1229
#define IDC_SETTINGS_SOCKS5_PASSWORD    1230
#define IDC_SETTINGS_UPLOAD_LINE_SPEED  1231
#define IDC_SETTINGS_DIRECTORIES        1232
#define IDC_SETTINGS_INCOMING           1233
#define IDC_SETTINGS_GENDER             1234
#define IDC_SETTINGS_DOWNLOAD_DIRECTORY 1235
#define IDC_SETTINGS_UNFINISHED_DOWNLOAD_DIRECTORY 1236
#define IDC_SETTINGS_PORT_TCP           1237
#define IDC_SETTINGS_DOWNLOAD_LIMITS    1238
#define IDC_NETWORK_WINFIREWALL_STATUS  1238
#define IDC_SETTINGS_DOWNLOADS_MAX      1239
#define IDC_SETTINGS_DOWNLOADS_SPEED_PAUSE 1240
#define IDC_SETTINGS_SPEEDS_NOT_ACCURATE 1241
#define IDC_SETTINGS_PUBLIC_HUB_LIST    1242
#define IDC_SETTINGS_PUBLIC_HUB_LIST_URL 1243
#define IDC_SETTINGS_PUBLIC_HUB_LIST_HTTP_PROXY 1244
#define IDC_BITTORRENT_PROGRAMM         1245
#define IDC_SETTINGS_SHARED_DIRECTORIES 1246
#define IDC_SETTINGS_FILES_MAX          1247
#define IDC_SETTINGS_SHARE_SIZE         1248
#define IDC_SETTINGS_UPLOADS_MIN_SPEED  1249
#define IDC_SETTINGS_UPLOADS_SLOTS      1250
#define IDC_SETTINGS_APPEARANCE_OPTIONS 1251
#define IDC_SETTINGS_DEFAULT_AWAY_MSG   1252
#define IDC_SETTINGS_LANGUAGE           1253
#define IDC_SETTINGS_DEFAULT_AWAY_MSG2  1254
#define IDC_SETTINGS_REQUIRES_RESTART   1255
#define IDC_SETTINGS_LOGGING            1256
#define IDC_SETTINGS_LOG_DIR            1257
#define IDC_SETTINGS_ROLLBACK           1258
#define IDC_SETTINGS_WRITE_BUFFER       1259
#define IDC_SETTINGS_MAX_TAB_ROWS       1260
#define IDC_SETTINGS_USER_MENU          1261
#define IDC_SETTINGS_KB                 1262
#define IDC_SETTINGS_B                  1263
#define IDC_SETTINGS_KBPS               1264
#define IDC_ADD_AS_FAVORITE             1265
#define IDC_REM_AS_FAVORITE             1266
#define IDC_AUTO_START_FAVORITE         1267
#define IDC_SETTINGS_SEARCH_HISTORY     1268
#define IDC_HELP_DONATE                 1269
#define IDC_HELP_HELP                   1270
#define IDC_ADLSP_SEARCH                1271
#define IDC_ADLSP_TYPE                  1272
#define IDC_ADLSP_SIZE_MIN              1273
#define IDC_ADLSP_SIZE_MAX              1274
#define IDC_ADLSP_UNITS                 1275
#define IDC_ADLSP_DESTINATION           1276
#define IDC_SETTINGS_SEPARATOR          1277
#define IDC_SETTINGS_RAW                1278
#define IDC_SETTINGS_CHAT               1279
#define IDC_SETTINGS_PM                 1280
#define IDC_SETTINGS_HUB_MENU           1281
#define IDC_REMOVE_FROM_FAVORITES       1282
#define IDC_SETTINGS_SEARCH_MENU        1283
#define IDC_SETTINGS_CONTEXT            1284
#define IDC_SETTINGS_PARAMETERS         1285
#define IDC_SETTINGS_NAME               1286
#define IDC_SETTINGS_COMMAND            1287
#define IDC_SETTINGS_HUB                1288
#define IDC_SETTINGS_TO                 1289
#define IDC_RESULT                      1290
#define IDC_SETTINGS_FORMAT             1291
#define IDC_PREVIEW_BROWSE              1292
#define IDC_SETTINGS_MAX_FINISHED_UPLOADS_L 1293
#define IDC_SETTINGS_MAX_FINISHED_DOWNLOADS_L 1294
#define IDC_REFRESH_FILE_LIST           1295
#define IDC_REFRESH_FILE_LIST_PURGE     1296
#define IDC_FLYLINK_DISCOVER            1297
#define IDC_SETTINGS_ONCE               1298
#define IDC_OPEN_DOWNLOADS              1299
#define IDC_SETTINGS_UPLOAD_BAR_COLOR   1300
#define IDC_PREVIEW_ARGUMENTS           1301
#define IDC_SETTINGS_DOWNLOAD_BAR_COLOR 1302
#define IDC_PREVIEW_EXTENSION           1303
#define IDC_AUTOSEGMENT                 1304
#define IDC_SETTINGS_SEGMENT_BAR_COLOR  1305
#define IDC_IDC_MULTISOURCE             1305
#define IDC_COPY_TTH                    1306
#define IDC_DONTBEGIN                   1307
#define IDC_EDIT1                       1308
#define IDC_CLIENT_NAME                 1309
#define IDC_CHUNKCOUNT                  1310
#define IDC_CLIENT_VERSION              1311
#define IDC_EDIT4                       1312
#define IDC_PASSWORD_HINT               1313
#define IDC_CLIENT_TAG                  1314
#define IDC_EDIT7                       1315
#define IDC_STATIC2                     1316
#define IDC_TOOLBAR_ACTUAL              1317
#define IDC_CLIENT_EXTENDED_TAG         1318
#define IDC_POPUPTYPE                   1319
#define IDC_STATIC3                     1320
#define IDC_CLIENT_LOCK                 1321
#define IDC_CLIENT_PK                   1322
#define IDC_MAX_HASH_SPEED              1323
#define IDC_TOOLBAR_IMAGE               1324
#define IDC_CLIENT_SUPPORTS             1325
#define IDC_TREE                        1326
#define IDC_STATIC4                     1327
#define IDC_SET_MIN_LENGHT_TTH_STREAM   1328
#define IDC_STATICb                     1329
#define IDC_IMAGEBROWSE                 1330
#define IDC_CLIENT_TESTSUR_RESPONSE     1331
#define IDC_SETTINGS_MAX_HASH_SPEED     1332
#define IDC_TOOLBAR_POSSIBLE            1333
#define IDC_CLIENT_USER_CON_COM         1334
#define IDC_SETTINGS_MBS                1335
#define IDC_MOUSE_OVER                  1336
#define IDC_CLIENT_STATUS               1337
#define IDC_STATIC5                     1338
#define IDC_SET_MIN_LENGHT_FOR_CHUNKS   1339
#define IDC_NORMAL                      1340
#define IDC_TOOLBAR_IMAGE_BOX           1341
#define IDC_VERSION_MISMATCH            1342
#define IDC_USE_EXTRA_VERSION           1343
#define IDC_CLIENT_ITEMS                1344
#define IDC_MAGNET_QUEUE                1345
#define IDC_ADD_CLIENT                  1346
#define IDC_MAGNET_SEARCH               1347
#define IDC_CLIENT_FORMATTED_TAG        1348
#define IDC_CHANGE_CLIENT               1349
#define IDC_MAGNET_REMEMBER             1350
#define IDC_MOVE_CLIENT_UP              1351
#define IDC_MAGNET_HASH                 1352
#define IDC_CLIENT_CONNECTION           1353
#define IDC_MAGNET_NAME                 1354
#define IDC_MOVE_CLIENT_DOWN            1355
#define IDC_REMOVE_CLIENT               1356
#define IDC_MAGNET_NOTHING              1357
#define IDC_ADD_LINE                    1358
#define IDC_MAGNET_DISP_NAME            1359
#define IDC_MAGNET_DISP_HASH            1360
#define IDC_MAGNET_TEXT                 1361
#define IDC_SETTINGS_TIME_STAMPS_FORMAT 1362
#define IDC_TIME_STAMPS_FORMAT          1363
#define IDC_CLIENT_CHEATING_DESCRIPTION 1364
#define IDC_SETTINGS_ONLY_HASHED        1365
#define IDC_FH_HUB                      1366
#define IDC_COMMENT                     1367
#define IDC_FH_IDENT                    1368
#define IDC_FH_NAME                     1369
#define IDC_MAXCOMPRESS                 1370
#define IDC_HASH_PROGRESS               1371
#define IDC_FH_ADDRESS                  1372
#define IDC_MAX_COMPRESSION             1373
#define IDC_HASH_INDEXING               1374
#define IDC_FH_HUB_DESC                 1375
#define IDC_MAX_COMP_SPIN               1376
#define IDC_FILES_PER_HOUR              1377
#define IDC_FH_NICK                     1378
#define IDC_HASH_SPEED                  1379
#define IDC_RELOAD_CLIENTS              1380
#define IDC_FH_PASSWORD                 1381
#define IDC_FH_USER_DESC                1382
#define IDC_TIME_LEFT                   1383
#define IDC_FH_EMAIL                    1384
#define IDC_SETTINGS_FAVORITE_DIRECTORIES 1385
#define IDC_FH_AWAY                     1386
#define IDC_SHUTDOWN_SPIN               1387
#define IDC_STATISTICS                  1388
#define IDC_FAVORITE_DIRECTORIES        1389
#define IDC_KB                          1390
#define IDC_SEG_NUMBER                  1391
#define IDC_CURRENT_FILE                1392
#define IDC_SEG_NUMBER_SPIN             1393
#define IDC_CURRENT_TTH                 1393
#define IDC_INTERVAL_SPIN               1394
#define IDC_LIST_ADD                    1395
#define IDC_SETTINGS_MAX_FINISHED_DOWNLOADS 1396
#define IDC_AUTO_SEARCH_EDIT            1397
#define IDC_MATCH_SPIN                  1398
#define IDC_LIST_EDIT_BOX               1399
#define IDC_AUTO_SEARCH_SPIN            1400
#define IDC_LIST_UP                     1401
#define IDC_BEGIN_EDIT                  1402
#define IDC_LIST_DOWN                   1403
#define IDC_BEGIN_SPIN                  1404
#define IDC_LIST_REMOVE                 1405
#define IDC_FAKE_SET                    1406
#define IDC_LIST_DESC                   1407
#define IDC_TIMEOUTS                    1408
#define IDC_LIST_LIST                   1409
#define IDC_DISCONNECTS                 1410
#define IDC_SOUNDLIST                   1411
#define IDC_RENAME                      1412
#define IDC_BAN_SLOTS                   1413
#define IDC_UPDATE_URL                  1414
#define IDC_REGEXP_TESTER_TEXT          1415
#define IDC_LIST_EDIT                   1416
#define IDC_BAN_SHARE                   1417
#define IDC_CHEAT                       1418
#define IDC_BAN_MSG                     1419
#define IDC_CHANGE_COLOR                1420
#define IDC_PORT_UDP                    1421
#define IDC_FAKE_SET2                   1422
#define IDC_USERLIST_IMAGE              1423
#define IDC_SETTINGS_PORT_UDP           1424
#define IDC_BAN_LIMIT                   1425
#define IDC_USERLIST                    1426
#define IDC_BANMSG_PERIOD               1427
#define IDC_SETTINGS_UPDATE_IP_INTERVAL 1428
#define IDC_IMPORT                      1429
#define IDC_BACKGROUND_IMAGE            1430
#define IDC_BAN_SLOTS_H                 1431
#define IDC_EXPORT                      1432
#define IDC_BACK_IMAGE                  1433
#define IDC_LOG_FORMAT                  1435
#define IDC_LOG_FILE                    1436
#define IDC_LOG_OPTIONS                 1437
#define IDC_SETTINGS_FILE_NAME          1438
#define IDC_ALTERNATE_COLOR             1439
#define IDC_FAKE_BOOLEANS               1440
#define IDC_SETTINGS_FILELIST_MENU      1441
#define IDC_PURGE                       1442
#define IDC_KBPS                        1443
#define IDC_MINUTES                     1444
#define IDC_SEARCH_HISTORY_SPIN         1445
#define IDC_KBPS2                       1446
#define IDC_PLAY                        1447
#define IDC_POPUPLIST                   1448
#define IDC_COMBO1                      1449
#define IDC_EDIT2                       1450
#define IDC_EDIT3                       1451
#define IDC_BIND_ADDRESS                1452
#define IDC_STATIC0                     1453
#define IDC_STATIC1                     1454
#define IDC_SETTINGS_BIND_ADDRESS_HELP  1455
#define IDC_GEOIP_COUNTRY_URL           1456
#define IDC_REGEXP_TESTER_BUTTON        1457
#define IDC_EDIT5                       1458
#define IDC_EDIT6                       1459
#define IDC_S                           1460
#define IDC_SETTINGS_WEB_BIND_ADDRESS_HELP 1461
#define IDC_FLAT                        1462
#define IDC_S2                          1463
#define IDC_WEB_BIND_ADDRESS            1464
#define IDC_FLAT_SPIN                   1465
#define IDC_STATIC6                     1466
#define IDC_DEFAULT                     1467
#define IDC_STATIC7                     1468
#define IDC_CONN_BORDER                 1469
#define IDC_CLIENT_PROFILE_RAW          1470
#define IDC_MULTISOURCE                 1471
#define IDC_SETTINGS_OUTGOING           1472
#define IDC_STATIC8                     1473
#define IDC_REGEXP_TESTER_COMBO         1474
#define IDC_LISTLEN                     1475
#define IDC_PUB_LIST_CONFIG             1477
#define IDC_ODC_STYLE                   1478
#define IDC_OVERRIDE                    1479
#define IDC_WINDOWS_STARTUP             1480
#define IDC_SETTINGS_PORTS              1481
#define IDC_SETTINGS_AUTO_OPEN          1482
#define IDC_SETTINGS_BIND_ADDRESS       1483
#define IDC_SETTINGS_WINDOWS_OPTIONS    1484
#define IDC_ADLSEARCH_ACTION            1485
#define IDC_PRIO_HIGHEST_SIZE           1486
#define IDC_SETTINGS_DHT                1487
#define IDC_WINDOWS_OPTIONS             1488
#define IDC_ADLSEARCH_RAW_ACTION        1489
#define IDC_PRIO_HIGH_SIZE              1490
#define IDC_REFRESH_SPIN                1491
#define IDC_DIRECT                      1492
#define IDC_PRIO_NORMAL_SIZE            1493
#define IDC_FIREWALL_UPNP               1495
#define IDC_PRIO_LOW_SIZE               1496
#define IDC_SHUTDOWNACTION              1497
#define IDC_FIREWALL_NAT                1498
#define IDC_SETTINGS_PRIO_HIGHEST       1499
#define IDC_READ_SPIN                   1500
#define IDC_POPUPGROUP                  1501
#define IDC_PARAM_NAME                  1502
#define IDC_FIREWALL_PASSIVE            1503
#define IDC_SETTINGS_PRIO_HIGH          1504
#define IDC_AUTO_SEARCH_LIMIT_SPIN      1505
#define IDC_PARAM_REGEXP                1506
#define IDC_DIRECT_OUT                  1507
#define IDC_SETTINGS_PRIO_NORMAL        1508
#define IDC_TAB_SPIN                    1509
#define IDC_USER                        1510
#define IDC_SOCKS5                      1511
#define IDC_SETTINGS_PRIO_LOW           1512
#define IDC_WRITE_SPIN                  1513
#define IDC_CHECK_MISMATCH              1514
#define IDC_PW                          1515
#define IDC_SETTINGS_KB3                1516
#define IDC_HASH_SPIN                   1517
#define IDC_CHECK_ADD_LIMIT             1518
#define IDC_AUTODETECT                  1519
#define IDC_SETTINGS_KB4                1520
#define IDC_BUFFER_SPIN                 1521
#define IDC_CHECK_ADD_SLOTS             1522
#define IDC_FAV_SEARCH_INTERVAL         1523
#define IDC_SETTINGS_KB5                1524
#define IDC_FAV_SEARCH_INTERVAL_BOX     1525
#define IDC_CD_GP                       1526
#define IDC_SET_MIN_LENGHT_TTH_STREAM_SPIN 1527
#define IDC_FAV_SEARCH_INTERVAL_SPIN    1528
#define IDC_SETTINGS_KB6                1529
#define IDC_SET_MIN_LENGHT_FOR_CHUNKS_SPIN 1530
#define IDC_SETTINGS_AUTOPRIO           1531
#define IDC_SET_MIN_LENGHT_FILE_FOR_MEDIAINFO_SPIN 1532
#define IDC_SETTINGS_SEGMENT            1533
#define IDC_BOLD_BOOLEANS               1534
#define IDC_PASSWORD_DESC               1535
#define IDC_SETTINGS_BOLD_CONTENTS      1536
#define IDC_PROT_START                  1537
#define IDC_ENABLE                      1538
#define IDC_SETTINGS_CONFIRM_OPTIONS    1539
#define IDC_PROFILE_MESSAGE             1540
#define IDC_PROT_TRAY                   1541
#define IDC_CONFIRM_OPTIONS             1542
#define IDC_PROT_CLOSE                  1543
#define IDC_PRIVATE                     1544
#define IDC_SOCKET_IN_BUFFER            1545
#define IDC_GROUP                       1546
#define IDC_FAVGROUP                    1547
#define IDC_SOCKET_OUT_BUFFER           1548
#define IDC_PORT_TLS                    1549
#define IDC_GROUPS                      1550
#define IDC_SETTINGS_SKIPLIST           1551
#define IDC_SETTINGS_SOCKET_OUT_BUFFER  1552
#define IDC_PROFILE_COUNT               1553
#define IDC_SKIPLIST_SHARE              1554
#define IDC_SETTINGS_SOCKET_IN_BUFFER   1555
#define IDC_PROFILE_VERSION             1556
#define IDC_HIDE_SHARE                  1557
#define IDC_ICON_SIZE                   1558
#define IDC_ICON_SIZE_HOVER             1559
#define IDC_RAW                         1560
#define IDC_LINK                        1561
#define IDC_GROUP_PROPERTIES            1562
#define IDC_SUPPORT_MAIL                1564
#define IDC_NAME_STATIC                 1565
#define IDC_TABSTEXT                    1566
#define IDC_THOLD                       1567
#define IDC_LINK_DANATE                 1568
#define IDC_PVS_STUDIO                  1569
#define IDC_SETTINGS_NOMINALBW          1570
#define IDC_TABSCOMBO                   1571
#define IDC_THOLD_STR                   1572
#define IDC_ENCODINGTEXT                1573
#define IDC_BUFFER_STR                  1574
#define IDC_RELOAD_BL                   1575
#define IDC_ENCODING                    1576
#define IDC_CONNECTION_DETECTION        1577
#define IDC_PG_STATUS                   1578
#define IDC_PG_DOWN                     1579
#define IDC_SETTINGS_USE_DHT            1580
#define IDC_PG_UP                       1581
#define IDC_BACK                        1582
#define IDC_PG_SEARCH                   1583
#define IDC_PG_LOG                      1584
#define IDC_SEP                         1585
#define IDC_GETIP                       1586
#define IDC_IPUPDATE                    1587
#define IDC_PRIO_FILE                   1588
#define IDC_ADD_FLYLINKDC_WINFIREWALL   1588
#define IDC_HIGHEST_STR                 1589
#define IDC_LOWEST_STR                  1590
#define IDC_HIGHEST                     1591
#define IDC_LOWEST                      1592
#define IDC_POPUP_TIME                  1593
#define IDC_POPUP_TIME_STR              1594
#define IDC_SETTINGS_ANTI_FRAG_FRAME    1595
#define IDC_SECS                        1596
#define IDC_SECONDARY_AWAY_MSG          1597
#define IDC_MISC_APPEARANCE             1598
#define IDC_TIME_AWAY                   1599
#define IDC_AWAY_START_TIME             1600
#define IDC_AWAY_END_TIME               1601
#define IDC_AWAY_TO                     1602
#define IDC_SECONDARY_AWAY_MESSAGE      1603
#define IDC_FLINK                       1604
#define IDC_CHECK1                      1605
#define IDC_PROFILE_INFO                1606
#define IDC_STEALTHY_STYLE              1607
#define IDC_PROT_FAVS                   1608
#define IDC_EXCL_CHECKS                 1609
#define IDC_STEALTH_BAN                 1611
#define IDC_SLOT_DL                     1612
#define IDC_PROTECT_PRIVATE             1613
#define IDC_SPEED_STR                   1614
#define IDC_BAN_FORCE_PM                1615
#define IDC_ALLOW_UPNP                  1616
#define IDC_GEOIP_USE_FLY               1617
#define IDC_TOP_SPEED                   1618
#define IDC_PROT_FAVS2                  1619
#define IDC_BAN_SKIP_OPS                1620
#define IDC_ENABLE_AUTO_BAN             1621
#define IDC_GEOIP_COUNTRY_USE           1622
#define IDC_MISC_GP                     1623
#define IDC_PROTECT_OP                  1624
#define IDC_ADV_MISC                    1625
#define IDC_SPEED_UP_STR                1626
#define IDC_PSR_DELAY_STR               1627
#define IDC_TOP_UP_SPEED                1628
#define IDC_PSR_DELAY                   1629
#define IDC_STEALTHY_STYLE_ICO          1630
#define IDC_OTHER                       1631
#define IDC_MISC_IGNORE                 1632
#define IDC_STEALTHY_STYLE_ICO_SPEED    1633
#define IDC_STEALTHY_STYLE_ICO_SPEEDIGNORE 1634
#define IDC_MISC_CHAT                   1635
#define IDC_COMBOBOXEX2                 1636
#define IDC_COMBOBOXEX1                 1637
#define IDC_POPUP_TYPE                  1638
#define IDC_COMPT                       1639
#define IDC_SHOW_JOINS                  1640
#define IDC_CHANGE                      1641
#define IDC_PROTECT_PRIVATE_SAY         1642
#define IDC_IGNORE_ADD                  1643
#define IDC_POPUP_TITLE_FONT            1644
#define IDC_SAVEAS                      1645
#define IDC_MAGNET_SAVEAS               1646
#define IDC_BAN_COLOR                   1647
#define IDC_IGNORELIST                  1649
#define IDC_IGNORELIST_EDIT             1650
#define IDC_IGNORE_REMOVE               1651
#define IDC_IGNORE_CLEAR                1652
#define IDC_POPUP_FONT                  1653
#define IDC_DUPE_EX1                    1654
#define IDC_DCLSTGEN_SAVEAS             1655
#define IDC_FILESHARE_ADD               1656
#define IDC_WIZARD_SHARE_REMOVE         1657
#define IDC_WIZARD_NETA_BTN_SETUPTEST   1658
#define IDC_INTEGRATION_IFACE_BTN_AUTOSTART 1659
#define IDC_PROT_USERS                  1660
#define IDC_PROT_PATTERNS               1661
#define IDC_PROT_DESC                   1662
#define IDC_PLAYER_COMBO                1663
#define IDC_BAN_STEALTH                 1664
#define IDC_RAW_TEXTS                   1665
#define IDC_IP_GET_IP                   1666
#define IDC_RAW4_TEXT                   1667
#define IDC_FLYLINK_TRUST_IP            1668
#define IDC_RAW5_TEXT                   1669
#define IDC_FLYLINK_PATH                1670
#define IDC_RAW1_TEXT                   1671
#define IDC_FLYLINK_TRUST_IP_BOX        1672
#define IDC_RAW2_TEXT                   1673
#define IDC_SLOT_CONTROL_GROUP          1674
#define IDC_RAW3_TEXT                   1675
#define IDC_TE_URLTEST                  1676
#define IDC_MINISLOTCONTROL             1677
#define IDC_MINISLOT_CONTROL_GROUP      1678
#define IDC_RAW1                        1679
#define IDC_AUTOBAN_HINT                1680
#define IDC_RAW2                        1681
#define IDC_RAW3                        1682
#define IDC_SETTINGS_ANTI_FRAG_MAX      1683
#define IDC_RAW4                        1684
#define IDC_SETTINGS_ANTI_FRAG          1685
#define IDC_RAW5                        1686
#define IDC_BUTTON3                     1687
#define IDC_DUPE_EX2                    1688
#define IDC_DCLSTGEN_COPYMAGNET         1689
#define IDC_FILESHARE_REMOVE            1690
#define IDC_WIZARD_SHARE_EDIT           1691
#define IDC_WIZARD_NETA_BTN_TEST        1692
#define IDC_INTEGRATION_IFACE_DESKTOP_IMG 1693
#define IDC_OPCHAT                      1694
#define IDC_ENABLE_WEBSERVER            1695
#define IDC_OPCHAT_STR                  1696
#define IDC_MAX_MSG_LENGTH              1700
#define IDC_MAX_MSG_LENGTH_STR          1701
#define IDC_POPUP_COLORS                1702
#define IDC_POPUP_BACKCOLOR             1703
#define IDC_POPUPFILE                   1704
#define IDC_POPUP_IMAGE_GP              1705
#define IDC_AWAY_START_TIME_SPIN        1706
#define IDC_POPUPBROWSE                 1707
#define IDC_AWAY_END_TIME_SPIN          1708
#define IDC_STATIC_ULC                  1709
#define IDC_POPUP_INPROGRAM             1710
#define IDC_POPUP_TIME_SPIN             1711
#define IDC_B2                          1712
#define IDC_OTHER_QUEUE_OPTIONS         1713
#define IDC_B1                          1714
#define IDC_M                           1716
#define IDC_MAGNET_URL_TEMPLATE         1718
#define IDC_MAGNET_URL_TEMPLATE_OLD     1719
#define IDC_EXCEPTION                   1720
#define IDC_DISCONNECTS_T               1722
#define IDC_GROUP_CUSTOMMENU            1723
#define IDC_DUPE_COLOR                  1724
#define IDC_TIMEOUT_T                   1725
#define IDC_CLIENT_ID                   1727
#define IDC_FAKESHARE_T                 1728
#define IDC_AUTOUPDATE_STARTATTIME      1729
#define IDC_WIZARD_NETA_USE_DHT         1730
#define IDC_GEOIP_CUSTOM_URL_USE        1731
#define IDC_FILELIST_DIFF               1733
#define IDC_SETTINGS_MEBIBITS           1734
#define IDC_CLIENT_ID_BOX               1735
#define IDC_LISTLEN_MISMATCH_T          1736
#define IDC_GEOIP_FLY_USE_URL           1737
#define IDC_SETTINGS_PASSWORD           1738
#define IDC_FILELIST_TOO_SMALL_T        1739
#define IDC_GEOIP_COUNTRY_USE_URL       1740
#define IDC_STYLES                      1741
#define IDC_SETTINGS_PASSWORD_HINT      1742
#define IDC_FILELIST_UNAVAILABLE_T      1743
#define IDC_AVAILABLE_STYLES            1744
#define IDC_PASSWORD                    1745
#define IDC_RAW_COMMANDS                1746
#define IDC_MESSAGES_BOOLEANS           1747
#define IDC_NO_LIMIT_FOR_FILE_LISTS     1748
#define IDC_SLOTASK                     1749
#define IDC_DONATE                      1750
#define IDC_SLOTASK_STR                 1751
#define IDC_TTH_IN_STREAM               1752
#define IDC_BTN_EXIT_ON_DONE            1753
#define IDC_TLS_PRIVATE_KEY_FILE        1754
#define IDC_EDIT_MAX_HASH_SPEED         1755
#define IDC_TLS_TRUSTED_CERTIFICATES_PATH 1756
#define IDC_DEPTH_STR                   1757
#define IDC_WMAGNET_TEMPL               1758
#define IDC_EWMAGNET_TEMPL              1759
#define IDC_CHECK_CHAT_ANIM             1760
#define IDC_CHECK_SMILE_SELECT_ANIM     1761
#define IDC_MAGNET_LINK                 1762
#define IDC_CUSTOM_MENU_URL             1763
#define IDC_MAGNET                      1764
#define IDC_RSS_ITEMS                   1765
#define IDC_AUTO_REFRESH_TIME           1767
#define IDC_RSSAUTOREFRESH_TIME_STR     1768
#define IDC_SETTINGS_AUTO_REFRESH_TIME  1769
#define IDC_RSS_AUTO_REFRESH_TIME       1770
#define IDC_AUTO_SEARCH_LIMIT           1771
#define IDC_SETTINGS_AUTO_SEARCH_LIMIT  1772
#define IDC_RSS_AUTOREFRESH_MIN         1773
#define IDC_CLOSE_ALL_PM                1774
#define IDC_SETTINGS_DOWNCONN           1775
#define IDC_ADD_RSS                     1776
#define IDC_CLOSE_ALL_OFFLINE_PM        1777
#define IDC_DOWNCONN                    1778
#define IDC_CHANGE_RSS                  1779
#define IDC_CLOSE_ALL_DIR_LIST          1780
#define IDC_REMOVE_RSS                  1781
#define IDC_CLOSE_ALL_SEARCH_FRAME      1782
#define IDC_SETTINGS_PORT_TLS           1783
#define IDC_RSS_AUTO_REFRESH_TIME_SPIN  1784
#define IDC_MATCH_ALL                   1785
#define IDC_RSSFEED_URL_LBL             1786
#define IDC_RSSFEED_URL                 1787
#define IDC_SETTINGS_PORT_DHT           1788
#define IDC_RSSFEED_NAME_LBL            1789
#define IDC_PORT_DHT                    1790
#define IDC_RSSFEED_NAME                1791
#define IDC_FLYLINK_TRUST_IP_URL        1792
#define IDC_FLYLINK_TRUST_IP_URL_STR    1793
#define IDC_PSWD_CHNG_STATIC            1794
#define IDC_PSWD_CHNG_OLD               1795
#define IDC_LINE2                       1796
#define IDC_LINE3                       1797
#define IDC_UPDATE_VERSION              1798
#define IDC_PSWD_CHNG_CONFIRM_NEW       1799
#define IDC_UPDATE_VERSION_CURRENT_LBL  1800
#define IDC_PSWD_CHNG_NEW               1801
#define IDC_UPDATE_FLYLINKDC            1802
#define IDC_UPDATE                      1803
#define IDC_EXCLUSIVE_HUB               1804
#define IDC_STATUS_HASH_PROGRESS        1805
#define IDC_CHANGE_HASH_SPEED           1806
#define IDC_CURRENT_HASH_SPEED          1807
#define IDC_TABS_OPTIONS                1808
#define IDC_SETTINGS_TABS_OPTIONS       1809
#define IDC_FAVGROUP_BOX                1810
#define IDC_PARAMS                      1811
#define IDC_AUTOUPDATE_USE              1812
#define IDC_DETECT_ID                   1813
#define IDC_SETTINGS_WEB_BIND_ADDRESS   1814
#define IDC_PERCENT_FAKE_SHARE_TOLERATED 1815
#define IDC_TIMEOUTS_NO                 1816
#define IDC_DISCONNECTS_NO              1817
#define IDC_BAN_SLOTS_NO                1818
#define IDC_BAN_SHARE_NO                1819
#define IDC_BAN_MSG_STR                 1820
#define IDC_BAN_LIMIT_NO                1821
#define IDC_BANMSG_PERIOD_NO            1822
#define IDC_ID_EDIT                     1823
#define IDC_BAN_SLOTS_NO_H              1824
#define IDC_REGEX_TESTER                1825
#define IDC_LEVEL                       1826
#define IDC_INFMAP_TYPE                 1827
#define IDC_USERLIST_COLORS             1828
#define IDC_SELECT_TAB_COLOR            1829
#define IDC_SAMPLE_TAB_COLOR            1830
#define IDC_RESET_TAB_COLOR             1831
#define IDC_UPDATE_WINDOW_TITLE         1832
#define IDC_AUTOPRIORITY                1833
#define IDC_USE_AUTOPRIORITY            1834
#define IDC_PRIO_LOWEST                 1835
#define IDC_MARK_AS_DOWNLOADED          1836
#define IDC_SETTINGS_ODC_MENUBAR        1837
#define IDC_SETTINGS_ODC_MENUBAR_USETWO 1838
#define IDC_SETTINGS_ODC_MENUBAR_COLOR  1839
#define IDC_SETTINGS_ODC_MENUBAR2       1840
#define IDC_PROGRESS_COLOR_DOWN_SHOW    1841
#define IDC_PROGRESS_COLOR_UP_SHOW      1842
#define IDC_FAVDIR_NAME                 1843
#define IDC_FAVDIR                      1844
#define IDC_FAVDIR_BROWSE               1845
#define IDC_FAVDIR_EXTENSION            1846
#define IDC_HUB_POSITION_COMBO          1847
#define IDC_HUB_POSITION_TEXT           1848
#define IDC_STATUS_AWAY_ON_OFF          1849
#define IDC_STATUS_DHT_ON               1850
#define IDC_STATUS_DHT_OFF              1851
#define IDC_PREVIEW_APP_INT             1852
#define IDC_BT_HELP                     1853
#define IDC_CONNECT_TO_FLYSUPPORT_HUB   1854
#define IDC_DISCONNECT_RAW              1855
#define IDC_TIMEOUT_RAW                 1856
#define IDC_FAKE_RAW                    1857
#define IDC_FILELIST_TOO_SMALL          1858
#define IDC_FILELIST_UNAVAILABLE        1859
#define IDC_SAVE                        1860
#define IDC_TOOLBAR_ADD                 1861
#define IDC_HOTBROWSE                   1862
#define IDC_TOOLBAR_REMOVE              1863
#define IDC_PREVIEW_NAME                1864
#define IDC_PREVIEW_APPLICATION         1865
#define IDC_TOOLBAR_HOT_IMAGE           1866
#define IDC_LIMITER                     1867
#define IDC_STEALTH                     1868
#define IDC_HELP_GEOIPFILE              1869
#define IDC_CHATCOLORS                  1870
#define IDC_MODCOLORS                   1871
#define IDC_LINK_BLOG                   1872
#define IDC_GENERATE_DCLST              1873
#define IDC_GENERATE_DCLST_FILE         1874
#define IDC_PRIORITY_PAUSED             1875
#define IDC_PRIORITY_LOWEST             1876
#define IDC_PRIORITY_LOW                1877
#define IDC_PRIORITY_NORMAL             1878
#define IDC_PRIORITY_HIGH               1879
#define IDC_PRIORITY_HIGHEST            1880
#define IDC_FLYLINK_GUARD_IP            1881
#define IDC_DEFAULT_POLICY_EXCEPT_STR   1882
#define IDC_ENABLE_IPGUARD              1885
#define IDC_DEFAULT_POLICY_STR          1886
#define IDC_DEFAULT_POLICY              1887
#define IDC_INTRO_IPGUARD               1888
#define IDC_REPLACE_NAME_EXISTS         1889
#define IDC_REPLACE_SIZE_EXISTS         1890
#define IDC_REPLACE_DATE_EXISTS         1891
#define IDC_REPLACE_DISP_NAME_EXISTS    1892
#define IDC_REPLACE_DISP_SIZE_EXISTS    1893
#define IDC_REPLACE_DISP_DATE_EXISTS    1894
#define IDC_REPLACE_NAME_NEW            1895
#define IDC_REPLACE_SIZE_NEW            1896
#define IDC_REPLACE_DISP_NAME_NEW       1897
#define IDC_REPLACE_DISP_SIZE_NEW       1898
#define IDC_REPLACE_CHANGE_NAME         1899
#define IDC_REPLACE_REPLACE             1900
#define IDC_REPLACE_RENAME              1901
#define IDC_REPLACE_SKIP                1902
#define IDC_REPLACE_APPLY               1903
#define IDC_REPLACE_DESCR               1904
#define IDC_REPLACE_BORDER_EXISTS       1905
#define IDC_REPLACE_BORDER_NEW          1906
#define IDC_ON_DOWNLOADING_SEGMENT      1907
#define IDC_ON_DOWNLOAD_ASK             1908
#define IDC_ON_DOWNLOAD_REPLACE         1909
#define IDC_ON_DOWNLOAD_AUTORENAME      1910
#define IDC_ON_DOWNLOAD_SKIP            1911
#define IDC_THEME_COMBO                 1912
#define IDC_THEME                       1913
#define IDC_THEME2                      1914
#define IDC_AUTOUPDATE_URL_LABEL        1915
#define IDC_AUTOUPDATE_URL              1916
#define IDC_AUTOUPDATE_SCHEDULE_LABEL   1917
#define IDC_AUTOUPDATE_RUNONSTARTUP     1918
#define IDC_AUTOUPDATE_AT               1919
#define IDC_AUTOUPDATE_LIST             1920
#define IDC_RSSFEED_CODEING_LBL         1921
#define IDC_RSSFEED_CODEING             1922
#define IDC_AUTOUPDATE_COMPONENTS       1923
#define IDC_AUTOUPDATE_COMPONENT_LABEL  1924
#define IDC_GRANT_IP_GROUP              1925
#define IDC_EXTRA_SLOT_BY_IP            1926
#define IDC_GRANT_SLOTS_FOR_OTHER_IP    1928
#define IDC_GRANTIP_INI_STAIC           1929
#define IDC_GRANTIP_INI                 1930
#define IDC_RTFDESCRIPTION              1931
#define IDC_STATICDESCRIPTION           1932
#define IDC_IGNOREUPDATE                1933
#define IDC_AUTOUPDATE_SERVER_BETA      1935
#define IDC_DCLS_ANOTHER_FOLDER         1936
#define IDC_AUTOUPDATE_USE_CUSTOM_SERVER 1937
#define IDC_DCLS_USE                    1938
#define IDC_DCLS_GENERATORBORDER        1939
#define IDC_DCLS_CREATE_IN_FOLDER       1940
#define IDC_DCLS_FOLDER                 1941
#define IDC_DCLS_MAGNETBORDER           1942
#define IDC_DCLSTGEN_NAMEBORDER         1943
#define IDC_DCLSTGEN_NAMESTATIC         1944
#define IDC_DCLSTGEN_NAME               1945
#define IDC_DCLSTGEN_MAGNET             1946
#define IDC_DCLSTGEN_SHARE              1947
#define IDC_DCLSTGEN_INFOBORDER         1948
#define IDC_DCLSTGEN_INFO_SIZESTATIC    1949
#define IDC_DCLST_GEN_INFOEDIT          1950
#define IDC_DCLSTGEN_INFO_FOLDERSSTATIC 1951
#define IDC_DCLSTGEN_INFO_FOLDERSEDIT   1952
#define IDC_DCLSTGEN_INFO_FILESSTATIC   1953
#define IDC_DCLSTGEN_INFO_FILESEDIT     1954
#define IDC_DCLSTGEN_PICT               1955
#define IDC_UPNPCHECK_PROGRESS          1956
#define IDC_DCLSTGEN_PROGRESS           1957
#define IDC_DOUBLE_CLICK_ACTION         1958
#define IDC_MAGNET_OPEN                 1959
#define IDC_DCLST_CLICK_STATIC          1960
#define IDC_DCLST_CLICK                 1961
#define IDC_DCLST_INCLUDESELF           1962
#define IDC_TECHSUPPORT_BORDER          1963
#define IDC_CONNECT_TO_SUPPORT_HUB      1964
#define IDC_FILESHARE_BORDER            1965
#define IDC_FILESHARE_LIST              1966
#define IDC_FILESHARE_REINDEX           1967
#define IDC_FILESHARE_BOOLEANS          1968
#define IDC_FILSHARE_OPTIONS_BORDER     1969
#define IDC_FILESHARE_WARNING           1970
#define IDC_GET_FAVORITE_DIR            1971
#define IDC_FAVORITE_DIR_EXT            1972
#define IDC_FAV_NAME2                   1973
#define IDC_PREV_NAME2                  1974
#define IDC_PREV_APPLICATION            1975
#define IDC_PREV_ARG                    1976
#define IDC_PREV_EXT                    1977
#define IDC_WIZARD_STARTUP_PICT         1978
#define IDC_WIZARD_STARTUP_TXT1         1979
#define IDC_WIZARD_STARTUP_TXT2         1980
#define IDC_WIZARD_STARTUP_TXT3         1981
#define IDC_WIZARD_LOGIN_LABEL          1982
#define IDC_WIZARD_LOGIN_EDIT           1983
#define IDC_WIZARD_DESC1_LABEL          1984
#define IDC_WIZARD_NICK_STATIC          1985
#define IDC_WIZARD_LABEL3               1986
#define IDC_WIZARD_NICK_STATIC1         1987
#define IDC_WIZARD_LABEL4               1988
#define IDC_WIZARD_NICK_STATIC2         1989
#define IDC_WIZARD_NICK_EMAIL_LABEL     1990
#define IDC_WIZARD_NICK_EMAIL           1991
#define IDC_WIZARD_NICK_DESC_LABEL      1992
#define IDC_WIZARD_NICK_DESCR           1993
#define IDC_WIZARD_DOWNLOAD_STATIC      1994
#define IDC_WIZARD_DOWNLOADDIR          1995
#define IDC_WIZARD_BROWSEDIR            1996
#define IDC_WIZARD_DOWNLOADTEMP_STATIC  1997
#define IDC_WIZARD_BROWSETEMPDIR        1998
#define IDC_WIZARD_TEMP_DOWNLOAD_DIRECTORY 1999
#define IDC_WIZARD_FINISH_LABEL1        2000
#define IDC_WIZARD_FINISH_LABEL2        2001
#define IDC_WIZARD_NICK_RND             2002
#define IDC_WIZARD_SHARE_STATIC         2003
#define IDC_WIZARD_NICK_RND2            2004
#define IDC_WIZARD_SHARE_LIST           2005
#define IDC_WIZARD_SHARE_ADD            2006
#define IDC_BUTTON4                     2007
#define IDC_WIZARD_SHARE_RENAME         2008
#define IDC_SOUND_ENABLE                2009
#define IDC_WIZARD_DOWNDIR_HELP         2010
#define IDC_DOWNLOAD_ASK_COMBO          2011
#define IDC_POPUP_ENABLE                2012
#define IDC_POPUP_MESSAGES_ENABLE       2013
#define IDC_POPUP_MESSAGEPANEL_ENABLE   2014
#define IDC_POPUP_TABS_ENABLE           2016
#define IDC_WIZARD_NET_IP_STATIC        2019
#define IDC_WIZARD_NET_IP_AUTO_IPUPDATE 2020
#define IDC_WIZARD_NET_IP_TITLE         2021
#define IDC_WIZARD_DETECT_IP            2022
#define IDC_WIZARD_NET_IP_DETECT_IP     2023
#define IDC_WIZARD_NETA_BTN_RAND        2024
#define IDC_WIZARD_NETA_USEDC           2025
#define IDC_WIZARD_NETA_TCP_ICO         2026
#define IDC_WIZARD_NETA_UDP_ICO         2027
#define IDC_WIZARD_NETA_AUTO_IPUPDATE   2028
#define IDC_WIZARD_NETA_BTN_SETUPROUTER 2029
#define IDC_WIZARD_NETA_TITLE           2030
#define IDC_WIZARD_NETA_FIREWALL_STATIC 2031
#define IDC_WIZARD_NETA_WINFIREWALL     2032
#define IDC_WIZARD_NETA_WINFIREWALL_BTN 2033
#define IDC_WIZARD_NETA_WINFIREWALL_STATIC2 2034
#define IDC_WIZARD_NETA_ROUTER_TITLE    2035
#define IDC_WIZARD_NETA_UPNP            2036
#define IDC_WIZARD_NETA_ROUTER_STATIC   2037
#define IDC_WIZARD_NETA_WINFIREWALL_ICO 2038
#define IDC_WIZARD_NETA_UPNP_ICO        2039
#define IDC_WIZARD_NETA_BTN_CHECKUPNP   2040
#define IDC_UPNPCHECK_STATIC            2041
#define IDC_SPEEDLIMITDLG_SLIDER        2044
#define IDC_SPEEDLIMITDLG_EDIT          2045
#define IDC_SECURITY_GROUP              2046
#define IDC_SECURITY_LIST               2047
#define IDC_INTEGRATION_SHELL_GROUP     2048
#define IDC_INTEGRATION_SHELL_BTN       2049
#define IDC_INTEGRATION_SHELL_TEXT      2050
#define IDC_INTEGRATION_INTERFACE_GROUP 2051
#define IDC_INTEGRATION_IFACE_STARTUP_TEXT 2052
#define IDC_SETTINGS_MAX_FINISHED_UPLOADS 2053
#define IDC_INT_PREVIEW_HTTP_SETUP_GROUP 2054
#define IDC_INT_PREVIEW_SERVER_PORT_STATIC 2055
#define IDC_INT_PREVIEW_SERVER_PORT     2056
#define IDC_INT_PREVIEW_SERVER_SPEED_STATIC 2057
#define IDC_INT_PREVIEW_SERVER_SPEED    2058
#define IDC_INT_PREVIEW_HTTP_CL_SETUP_GROUP 2059
#define IDC_INT_PREVIEW_HTTP_CL_SETUP_PATH 2060
#define IDC_BTN_SELECT                  2061
#define IDC_INT_PREVIEW_HTTP_CL_SETUP_PATH_EDIT 2062
#define IDC_INT_PREVIEW_LIST            2063
#define IDC_MAGNET_START_VIEW           2064
#define IDC_PRV_DLG_SERVER_GROUP        2065
#define IDC_PRV_DLG_SERVER_STATE_STATIC 2066
#define IDC_PRV_DLG_SERVER_STATE        2067
#define IDC_PRV_DLG_SERVER_STATE_BTN    2068
#define IDC_PRV_DLG_LOG_LST             2069
#define IDC_PRV_DLG_VIDEO_NAME_STATIC   2070
#define IDC_PRV_DLG_VIDEO_NAME          2071
#define IDC_PRV_DLG_VIDEO_STATUS        2072
#define IDC_PRV_DLG_LOG_GROUP           2073
#define IDC_GEOIP_USE_CUSTOM            2074
#define IDC_GEOIP_LOCATION_NAME_STATIC  2075
#define IDC_GEOIP_LOCATION_NAME_STATIC1 2076
#define IDC_GEOIP_LOCATION_NAME_STATIC2 2077
#define IDC_GEOIP_CUSTOM_NAME           2078
#define IDC_GEOIP_CUSTOM_URL            2079
#define IDC_GEOIP_FLY_NAME              2080
#define IDC_GEOIP_FLY_URL               2081
#define IDC_GEOIP_COUNTRY_NAME          2082
#define IDC_PROVIDER_USE_RESOURCES      2083
#define IDC_PROVIDER_URL_GROUP          2084
#define IDC_PROVIDER_URL                2085
#define IDC_PROVIDER_USELIST_PAGE       2086
#define IDC_PROVIDER_USE_LIST           2087
#define IDC_FUNCTIONAL_IS_DISABLED      2088
#define IDC_INTEGRATION_BOOLEANS        2089
#define IDC_LANG_LINK                   2090
#define IDC_CHECK_ADD_TO_DESCRIPTION    2091
#define IDC_FLY_LOG_SQLITE              2092
#define IDC_FLY_LOG_TEXT                2093
#define IDC_SAVE_PASSWORD               2094
#define IDC_WRITE_LOGS                  2095
#define IDC_ISP_MORE_INFO_LINK          2096
#define IDC_TABCOLOR_LIST               2097
#define IDC_MESSAGES_CHAT_BOOLEANS      2098
#define IDC_FAKE_CHAT_BOOLEANS          2099
#define IDC_SETTINGS_SECONDARY_AWAY_MSG 2100
#define IDC_EXTRASLOTSSPIN              2101
#define IDC_EXTRA_DOWN_SLOT             2102
#define IDC_EXTRA_DOWNLOADS_MAX         2103
#define IDC_ERROR_COLOR                 2104
#define IDC_UPTIME                      2105
#define IDC_CZDC_SLOW_DISCONNECT        2106
#define IDC_CZDC_I_DOWN_SPEED           2107
#define IDC_BACK_COLOR                  2108
#define IDC_REMOVE_IF                   2109
#define IDC_CZDC_TIME_DOWN              2110
#define IDC_TEXT_STYLE                  2111
#define IDC_TEXT_COLOR                  2112
#define IDC_CZDC_H_DOWN_SPEED           2113
#define IDC_PREVIEW                     2114
#define IDC_CZDC_MIN_FILE_SIZE          2115
#define IDC_I_DOWN_SPEED                2116
#define IDC_PREVIEW2                    2117
#define IDC_TEXT_STYLES                 2118
#define IDC_REMOVE_IF_BELOW             2119
#define IDC_EXTRA_SLOTS                 2120
#define IDC_EXTRA_SLOTS_SPIN            2121
#define IDC_SMALL_FILE_SIZE             2122
#define IDC_SMALL_FILE_SIZE_SPIN        2123
#define IDC_BLACK_AND_WHITE             2124
#define IDC_DEFAULT_STYLES              2125
#define IDC_COPY_APPLICATION            2126
#define IDC_COPY_FILENAME               2127
#define IDC_COPY_PATH                   2128
#define IDC_TIME_DOWN                   2129
#define IDC_COPY_SIZE                   2130
#define IDC_OPEN_HUB_LOG                2131
#define IDC_OPEN_USER_LOG               2132
#define IDC_H_DOWN_SPEED                2133
#define IDC_SETTINGS_KBPS5              2134
#define IDC_SETTINGS_KBPS7              2135
#define IDC_MANAGE_GROUPS               2136
#define IDC_UPLOADSPEEDSPIN             2137
#define IDC_DOWNLOADSPEEDSPIN           2138
#define IDC_NONE                        2139
#define IDC_SETTINGS_KBPS6              2140
#define IDC_SETTINGS_MB                 2141
#define IDC_SETTINGS_MB2                2142
#define IDC_SETTINGS_MINUTES            2143
#define IDC_SETTINGS_MB3                2144
#define IDC_I_DOWN_SPEED_SPIN           2145
#define IDC_TIME_DOWN_SPIN              2146
#define IDC_H_DOWN_SPEED_SPIN           2147
#define IDC_ADD_NICK_TO_CHAT            2148
#define IDC_MIN_FILE_SIZE_SPIN          2149
#define IDC_SELECT_USER                 2150
#define IDC_REMOVE_SPIN                 2151
#define IDC_COPY_ACTUAL_LINE            2152
#define IDC_COPY_DESCRIPTION            2153
#define IDC_COPY_EMAIL_ADDRESS          2154
#define IDC_AUTOSCROLL_CHAT             2155
#define IDC_WHOIS_IP                    2156
#define IDC_BAN_IP                      2157
#define IDC_UNBAN_IP                    2158
#define IDC_CLIENT                      2159
#define IDC_COPY_URL                    2160
#define IDC_BOLD_AUTHOR_MESS            2161
#define IDC_WINDOWS_STYLE_URL           2162
#define IDC_IGNORE_BY_NAME              2163
#define IDC_WINAMP_HELP                 2165
#define IDC_RATIOMSG_HELP               2166
#define IDC_MX_UP_SP_LMT_NORMAL         2167
#define IDC_MX_DW_SP_LMT_NORMAL         2168
#define IDC_MX_UP_SP_LMT_TIME           2169
#define IDC_MX_DW_SP_LMT_TIME           2170
#define IDC_TIME_LIMITING               2171
#define IDC_BW_START_TIME               2172
#define IDC_BW_END_TIME                 2173
#define IDC_UPLOADSPEEDSPIN_TIME        2174
#define IDC_DOWNLOADSPEEDSPIN_TIME      2175
#define IDC_GRANTSLOT                   2176
#define IDC_GRANTSLOT_HOUR              2177
#define IDC_GRANTSLOT_DAY               2178
#define IDC_GRANTSLOT_WEEK              2179
#define IDC_GRANTSLOT_PERIOD            2180
#define IDC_UNGRANTSLOT                 2181
#define IDC_UPLOAD_QUEUE                2182
#define IDC_THROTTLE_ENABLE             2183
#define IDC_DISCONNECTING_ENABLE        2184
#define IDC_WINAMP                      2185
#define IDC_SEGMENTED_ONLY              2186
#define IDC_RATIOMSG                    2187
#define IDC_PROGRESS_TEXT_COLOR_DOWN    2188
#define IDC_PROGRESS_TEXT_COLOR_UP      2189
#define IDC_CZDC_SOUND                  2190
#define IDC_CZDC_TRANSFER_LIMITING      2191
#define IDC_CZDC_UP_SPEEED              2192
#define IDC_CZDC_DW_SPEEED              2193
#define IDC_CZDC_TO                     2194
#define IDC_CZDC_SECONDARY_TRANSFER     2195
#define IDC_CZDC_PROGRESS_COLOR         2196
#define IDC_CZDC_PROGRESS_TEXT          2197
#define IDC_INTERVAL_TEXT               2198
#define IDC_MATCH_QUEUE_TEXT            2199
#define IDC_CZDC_WINAMP                 2200
#define IDC_SETCZDC_CHAT_LINES          2201
#define IDC_CZDC_RATIOMSG               2202
#define IDC_LENGHT_FILE_TTH_IN_STREAM   2203
#define IDC_CZDC_PREVIEW                2204
#define IDC_LENGHT_FILE_TO_CHUNKS_DOWNLOAD 2205
#define IDC_CZDC_DW_SPEEED1             2206
#define IDC_CZDC_UP_SPEEED1             2207
#define IDC_SETTINGS_KBPS1              2208
#define IDC_SETTINGS_KBPS2              2209
#define IDC_SETTINGS_KBPS3              2210
#define IDC_SETTINGS_KBPS4              2211
#define IDC_CZDC_SMALL_SLOTS            2212
#define IDC_CZDC_SMALL_SIZE             2213
#define IDC_CZDC_NOTE_SMALL             2214
#define IDC_USER_CMD_DESCRIPTION        2215
#define IDC_USER_CMD_EXAMPLE            2216
#define IDC_COPY_EXACT_SHARE            2217
#define IDC_COPY_IP                     2218
#define IDC_COPY_NICK_IP                2219
#define IDC_CHAT_LINES                  2220
#define IDC_CHAT_LINES_SPIN             2221
#define IDC_COPY_ALL                    2222
#define IDC_COPY_LINK                   2223
#define IDC_COPY_WMLINK                 2224
#define IDC_REBUILD_TOOLBAR             2225
#define IDC_MAGNET_SIZE                 2226
#define IDC_MAGNET_DISP_SIZE            2227
#define IDC_TIMESTAMP_HELP              2228
#define IDC_USERLIST_DBLCLICK           2229
#define IDC_TRANSFERLIST_DBLCLICK       2230
#define IDC_USERLISTDBLCLICKACTION      2231
#define IDC_TRANSFERLISTDBLCLICKACTION  2232
#define IDC_CHATDBLCLICKACTION          2233
#define IDC_CHAT_DBLCLICK               2234
#define IDC_HEADER_MENU                 2235
#define IDC_FAVUSERLISTDBLCLICKACTION   2236
#define IDC_FAVUSERLIST_DBLCLICK        2237
#define IDC_MAGNETURLCLICKACTION        2238
#define IDC_MAGNETURLLIST_CLICK         2239
#define IDC_SPEED_NORMAL                2240
#define IDC_SPEED_SUPER                 2241
#define IDC_SPEED_BAN                   2242
#define IDC_SPEED_128K                  2243
#define IDC_SPEED_512K                  2244
#define IDC_SPEED_1024K                 2245
#define IDC_SPEED_2048K                 2246
#define IDC_SPEED_4096K                 2247
#define IDC_SPEED_10240K                2248
#define IDC_SPEED_MANUAL                2249
#define IDC_U_PRIO_EXTRA                2251
#define IDC_U_PRIO_HIGH                 2252
#define IDC_U_PRIO_NORMAL               2253
#define IDC_U_PRIO_LOW                  2254
#define IDC_SET_MIN_LENGHT_FILE_TO_MEDIAINFO 2255
#define IDC_SET_MIN_LENGHT_FOR_MEDIAINFO 2256
#define IDC_PM_NORMAL                   2257
#define IDC_PM_IGNORED                  2258
#define IDC_PM_FREE                     2259
#define IDC_ASK_SLOT                    2260
#define IDC_BITZI_LOOKUP                2261
#define IDC_DOWNLOAD                    2262
#define IDC_DOWNLOADTO                  2263
#define IDC_RECENTS                     2264
#define IDC_FAVORITES                   2265
#define IDC_FOLLOW                      2266
#define IDC_SEND_MESSAGE                2267
#define IDC_MESSAGEPANEL                2268
#define IDC_FILTER_FOCUS                2269
#define IDC_GET_USER_RESPONSES          2270
#define IDC_REPORT                      2271
#define IDC_CHECKLIST                   2272
#define IDC_ADD_MAGNET                  2273
#define IDC_RSS                         2274
#define IDC_BOLD                        2275
#define IDC_ITALIC                      2276
#define IDC_UNDERLINE                   2277
#define IDC_STRIKE                      2278
#define IDC_COLOR                       2279
#define IDC_COLLAPSED                   2280
#define IDC_STARTVIEW_EXISTING_FILE     2281
#define IDC_MIN_LENGHT_FILE_TO_MEDIAINFO 2282
#define IDC_PAUSE                       2283
#define IDC_PARTIAL_SLOTS               2284
#define IDC_PARTIAL_SLOTS_SPIN          2285
#define IDC_SETTINGS_PARTIAL_SLOTS      2286
#define IDC_AUTO_SLOTS                  2287
#define IDC_AUTO_SLOTS_SPIN             2288
#define IDC_SETTINGS_AUTO_SLOTS         2289
#define IDC_RECHECK                     2290
#define IDC_TEXT_FAKEPERCENT            2291
#define IDC_EDIT_HUB_PROP               2292
#define IDC_POPUP_W                     2293
#define IDC_POPUP_H                     2294
#define IDC_POPUP_W_STR                 2295
#define IDC_POPUP_H_STR                 2296
#define IDC_POPUP_W_SPIN                2297
#define IDC_POPUP_H_SPIN                2298
#define IDC_POPUP_TRANSP_STR            2299
#define IDC_POPUP_TRANSP_SLIDER         2300
#define IDC_POPUP_SHOW_INFO_TIPS_ENABLE 2301
#define IDC_PROPPAGE_TRANSPARENCY       2302
#define IDC_PROPPAGE_WIKIHELP           2303
#define IDC_THANKS_STATIC               2304
#define IDC_LINKS_STATIC                2305
#define IDC_STATISTICS_STATIC           2306
#define IDC_SIDEPRO_STATIC              2307
#define IDC_MAGNET_PIC                  2315
#define IDC_PM_PASSWORD_HELP            2316
#define IDC_PM_PASSWORD_GENERATE        2317
#define IDC_PROTECT_PRIVATE_RND         2318
#define IDC_PASSWORD_OK_HINT            2319
#define IDC_SETTINGS_PASSWORD_OK_HINT   2320
#define IDC_USE_CUSTOM_MENU             2321
#define IDC_POPUP_AWAY                  2322
#define IDC_POPUP_MINIMIZED             2323
#define IDC_SOUNDS_COMBO                2324
#define IDC_SOUNDS                      2325
#define IDC_SEARCH_SIZEMODE             2326
#define IDC_SEARCH_SIZE                 2327
#define IDC_SEARCH_MODE                 2328
#define IDC_SEARCH_WIKIHELP             2329
#define IDC_SEARCH_FILE_IN_GOOGLE       2330
#define IDC_SEARCH_FILE_IN_YANDEX       2332
#define IDC_COPY_HUB_URL                2333
#define IDC_COPY_FULL_MAGNET_LINK       2334
#define IDC_HUBS_SWITCHPANELS           2335
#define IDC_UPDATE_FILES                2336
#define IDC_SET_TTH_MEDIAINFO_SERVER    2337
#define IDC_GET_TTH_MEDIAINFO_SERVER    2338
#define IDC_SPEED_STATIC                2339
#define IDC_COPY_FLYSERVER_INFORM       2340
#define IDC_FLY_SERVER_LISTBOX          2341
#define IDC_REFRESH_MEDIAINFO           2342
#define IDC_MEDIAINFORM_STATIC          2343
#define IDC_SEARCH_FORGET               2344
#define IDC_MEDIAINFO_SIZE_TXT          2345
#define IDC_MEDIAINFO_SIZE              2346
#define IDC_MEDIAINFO_SIZE_MB           2347
#define IDC_THEME_COMBO2                2348
#define IDC_VIEW_FLYSERVER_INFORM       2349
#define IDC_USE_FLY_SERVER_STATICTICS_SEND 2350
#define IDC_ABOUTTAB                    2351
#define IDC_CONVERT_TTH_HISTORY         2352
#define IDC_COPY_TAG                    2353
#define IDC_NETWORK_TEST_PORT_TCP_ICO   2354
#define IDC_COPY_CID                    2355
#define IDC_NETWORK_TEST_PORT_UDP_ICO   2356
#define IDC_NETWORK_TEST_PORT_TLS_TCP_ICO 2357
#define IDC_NETWORK_TEST_PORT_TCP_ICO4  2358
#define IDC_NETWORK_TEST_PORT_DHT_UDP_ICO 2359
#define IDC_NETWORK_WINFIREWALL_ICO     2360
#define IDC_BTN_REFRESH_FILELIST        2361
#define IDC_WIFI_ROUTER_ICO             2362
#define IDC_EDIT_MAX_HASH_SPEED_SLIDER  2363
#define IDC_LOCATION_CITY               2364
#define IDC_LOCATION_CITY_DESCRIPTION   2365
#define IDC_LOCATION_PROVIDER_DESCRIPTION 2366
#define IDC_STATIC_GATEWAY              2367
#define IDC_LOCATION_PROVIDER           2368
#define IDC_FORCE_PASSIVE_MODE          2369
#define IDC_COPY_ANTIVIRUS_DB_INFO      2370
#define IDC_LOCATION_COUNTRY_DESCRIPTION 2371
#define IDC_LOCATION_COUNTRY            2372
#define IDC_COPY_GEO_LOCATION           2373
#define IDC_ISP_TREE                    2374
#define IDC_TOTAL_UPTIME                2375
#define IDC_SYSUPTIME                   2376
#define IDC_TOTAL_MESSAGES              2377
#define IDC_DOWNLOAD_TARGET             2500
#define IDC_FLYLINKDC_LOCATION          2501
#define IDC_DOWNLOAD_TARGET_DIR         3000
#define IDC_SELECT_WINDOW               3500
#define IDC_USER_COMMAND                4000
#define IDC_DOWNLOAD_FAVORITE_DIRS      4500
#define IDC_DOWNLOAD_WHOLE_FAVORITE_DIRS 5000
#define IDC_EMOMENU                     5500
#define IDC_COPY                        6000
#define IDC_CUSTOM_MENU                 6500
#define IDC_CUSTOM_MENU100              6600
#define IDC_PORTAL_BROWSER              6601
#define IDC_PORTAL_BROWSER49            6650
#define IDC_SEGMENTONE                  6701
#define IDC_SEGMENTTWO                  6702
#define IDC_SEGMENTTHREE                6703
#define IDC_SEGMENTFOUR                 6704
#define IDC_SEGMENTFIVE                 6705
#define IDC_SEGMENTSIX                  6706
#define IDC_SEGMENTSEVEN                6707
#define IDC_SEGMENTEIGHT                6708
#define IDC_SEGMENTNINE                 6709
#define IDC_SEGMENTTEN                  6710
#define IDC_SEGMENTFIFTY                6750
#define IDC_SEGMENTHUNDRED              6800
#define IDC_SEGMENTHUNDRED_FIFTY        6850
#define IDC_SEGMENTTWO_HUNDRED          6900
#define IDC_BROWSELIST                  7000
#define IDC_REMOVE_SOURCE               7100
#define IDC_REMOVE_SOURCES              7200
#define IDC_PM                          7300
#define IDC_READD                       7400
#define IDC_PREVIEW_APP                 7500
#define IDC_BROWSESQLLIST               7600
#define IDC_FLY_SERVER_EXPLORER         7601
#define ID_TOGGLE_TOOLBAR               32771
#define ID_TOGGLE_QSEARCH               32772
#define ID_VIEW_TRANSFER_VIEW           32773
#define ID_GET_TTH                      32774
#define ID_SHELLCONTEXTMENU_MIN         32775
#define ID_SHELLCONTEXTMENU_MAX         32776
#define ID_FILE_CONNECT                 32777
#define ID_FILE_SETTINGS                32778
#define ID_FILE_RECONNECT               32779
#define ID_FILE_SEARCH                  32780
#define ID_FILE_QUICK_CONNECT           32781
#define ID_HELP_ACCELERATOR             32782
#define ID_FILE_SETTINGS_WIZARD         32783
#define ID_WINDOW_MINIMIZE_ALL          32784
#define ID_WINDOW_RESTORE_ALL           32785
#define ID_TEXT_TRANSCODE               32786
#define ID_MEDIA_MENU_WINAMP_START      32787
#define ID_DISCONNECT                   32788
#define ID_VIEW_TRANSFER_VIEW_TOOLBAR   32789
#define ID_MEDIA_MENU_WINAMP_END        32807
#define IDC_PROGRESS                    32809
#define IDC_TIME                        32810
#define IDC_SEARCH_PASSIVE              32811
#define IDC_SEARCH_UDP_PORT_TEST        32812

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        301
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         2378
#define _APS_NEXT_SYMED_VALUE           2423
#endif
#endif
