version: r504-master-x64{build}

branches:
  only:
    - master

image: Visual Studio 2019

clone_depth: 1


platform:
  - x64

configuration:
  - Release

build:
  project: FlylinkDC_2017.sln
  verbosity: minimal
