/*
#define SQLITE_OMIT_COMPOUND_SELECT
#define SQLITE_OMIT_CONFLICT_CLAUSE
#define SQLITE_OMIT_FOREIGN_KEY
#define SQLITE_OMIT_INTEGRITY_CHECK
#define SQLITE_OMIT_TRIGGER
#define SQLITE_OMIT_AUTOVACUUM
#define SQLITE_OMIT_UTF16
*/
// #define SQLITE_OMIT_AUTHORIZATION
// #define SQLITE_OMIT_EXPLAIN
// #define SQLITE_OMIT_FLOATING_POINT // необходимо для логов в sqlite ( datetime('now') )

#define SQLITE_MAX_ATTACHED 7

// TODO - Блокировки внутри sqlite лишние
#define SQLITE_THREADSAFE 0
#define THREADSAFE 0

#define SQLITE_DEFAULT_CACHE_SIZE 8000
#define SQLITE_DEFAULT_TEMP_CACHE_SIZE 2000
