; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; customer: ppa@lipetsk.ru

[Setup]
UsePreviousLanguage=no
OutputBaseFilename=SetupFlylinkDC
[Files]

Source: "..\compiled\FlylinkDC.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\compiled\PortalBrowser\PortalBrowser.dll"; DestDir: "{app}\PortalBrowser";  Components: PortalBrowser; Flags: ignoreversion

#include "FlylinkDC.hss"
