; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; customer: ppa@lipetsk.ru

;#define PPA_PORTAL_MERGE
#define YANDEX_VID_PREFIX 501

[Setup]
OutputBaseFilename=SetupFlylinkDC-x86

#include "FlylinkDC-x86.hss"
#include "FlylinkDC.hss"