; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; customer: ppa@lipetsk.ru

#define PPA_PORTAL_MERGE
#define YANDEX_VID_PREFIX 502

[Setup]
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
OutputBaseFilename=SetupFlylinkDC-x64

#include "FlylinkDC-x64.hss"
#include "FlylinkDC.hss"